# Generated by Django 2.2.24 on 2021-10-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_cliente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
