# Generated by Django 2.2.24 on 2021-10-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_unidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidade',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
