# Generated by Django 2.2.24 on 2021-10-24 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0005_unidade_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidade',
            name='pagamento',
            field=models.CharField(choices=[('À Vista', 'À Vista'), ('180 Parcelas', '180 Parcelas')], max_length=30, null=True, verbose_name='Forma de Pagamento'),
        ),
    ]
