# Generated by Django 2.2.24 on 2021-10-24 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autenticacao', '0006_auto_20211024_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(max_length=50, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=50)),
                ('localizacao', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicao_pagamento', models.CharField(choices=[('À Vista', 'À Vista'), ('180 Parcelas', '180 Parcelas')], max_length=30, null=True, verbose_name='Forma de Pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.Cliente', verbose_name='cliente')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='corretor')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autenticacao.Imovel', verbose_name='imovel')),
            ],
        ),
        migrations.DeleteModel(
            name='Unidade',
        ),
    ]
