# Generated by Django 2.2.24 on 2021-10-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0008_imovel_disponivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='comissao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
